const std = @import("std");
const ngx = @import("ngx.zig");
const expectEqual = std.testing.expectEqual;

pub const ngx_buf_t = ngx.ngx_buf_t;
pub const ngx_output_chain_ctx_t = ngx.ngx_output_chain_ctx_t;
pub const ngx_listening_t = ngx.ngx_listening_t;
pub const ngx_connection_t = ngx.ngx_connection_t;
pub const ngx_file_t = ngx.ngx_file_t;
pub const ngx_temp_file_t = ngx.ngx_temp_file_t;
pub const ngx_ext_rename_file_t = ngx.ngx_ext_rename_file_t;
pub const ngx_url_t = ngx.ngx_url_t;
pub const ngx_open_file_info_t = ngx.ngx_open_file_info_t;
pub const ngx_cached_open_file_t = ngx.ngx_cached_open_file_t;
pub const ngx_resolver_node_t = ngx.ngx_resolver_node_t;
pub const ngx_resolver_t = ngx.ngx_resolver_t;
pub const ngx_resolver_ctx_t = ngx.ngx_resolver_ctx_t;
pub const ngx_slab_pool_t = ngx.ngx_slab_pool_t;
pub const ngx_variable_value_t = ngx.ngx_variable_value_t;
pub const ngx_syslog_peer_t = ngx.ngx_syslog_peer_t;
pub const ngx_event_t = ngx.ngx_event_t;
pub const ngx_peer_connection_t = ngx.ngx_peer_connection_t;
pub const ngx_event_pipe_t = ngx.ngx_event_pipe_t;
pub const ngx_http_file_cache_node_t = ngx.ngx_http_file_cache_node_t;
pub const ngx_http_cache_t = ngx.ngx_http_cache_t;
pub const ngx_http_listen_opt_t = ngx.ngx_http_listen_opt_t;
pub const ngx_http_core_srv_conf_t = ngx.ngx_http_core_srv_conf_t;
pub const ngx_http_addr_conf_t = ngx.ngx_http_addr_conf_t;
pub const ngx_http_conf_addr_t = ngx.ngx_http_conf_addr_t;
pub const ngx_http_core_loc_conf_t = ngx.ngx_http_core_loc_conf_t;
pub const ngx_http_header_out_t = ngx.ngx_http_header_out_t;
pub const ngx_http_headers_in_t = ngx.ngx_http_headers_in_t;
pub const ngx_http_request_body_t = ngx.ngx_http_request_body_t;
pub const ngx_http_connection_t = ngx.ngx_http_connection_t;
pub const ngx_http_request_t = ngx.ngx_http_request_t;
pub const ngx_http_script_engine_t = ngx.ngx_http_script_engine_t;
pub const ngx_http_script_compile_t = ngx.ngx_http_script_compile_t;
pub const ngx_http_script_regex_code_t = ngx.ngx_http_script_regex_code_t;
pub const ngx_http_script_regex_end_code_t = ngx.ngx_http_script_regex_end_code_t;
pub const ngx_http_compile_complex_value_t = ngx.ngx_http_compile_complex_value_t;

pub const ngx_array_t = ngx.ngx_array_t;

test "ngx data types" {
    try expectEqual(@sizeOf(ngx_buf_t), 80);
    try expectEqual(@sizeOf(ngx_output_chain_ctx_t), 104);
    try expectEqual(@sizeOf(ngx_listening_t), 296);
    try expectEqual(@sizeOf(ngx_connection_t), 224);
    try expectEqual(@sizeOf(ngx_file_t), 200);
    try expectEqual(@sizeOf(ngx_temp_file_t), 248);
    try expectEqual(@sizeOf(ngx_ext_rename_file_t), 40);
    try expectEqual(@sizeOf(ngx_url_t), 224);
    try expectEqual(@sizeOf(ngx_open_file_info_t), 104);
    try expectEqual(@sizeOf(ngx_cached_open_file_t), 144);
    try expectEqual(@sizeOf(ngx_resolver_node_t), 184);
    try expectEqual(@sizeOf(ngx_resolver_t), 512);
    try expectEqual(@sizeOf(ngx_resolver_ctx_t), 224);
    try expectEqual(@sizeOf(ngx_slab_pool_t), 200);
    try expectEqual(@sizeOf(ngx_variable_value_t), 16);
    try expectEqual(@sizeOf(ngx_syslog_peer_t), 392);
    try expectEqual(@sizeOf(ngx_event_t), 96);
    try expectEqual(@sizeOf(ngx_peer_connection_t), 112);
    try expectEqual(@sizeOf(ngx_event_pipe_t), 280);
    try expectEqual(@sizeOf(ngx_http_file_cache_node_t), 120);
    try expectEqual(@sizeOf(ngx_http_cache_t), 608);
    try expectEqual(@sizeOf(ngx_http_listen_opt_t), 72);
    try expectEqual(@sizeOf(ngx_http_core_srv_conf_t), 168);
    try expectEqual(@sizeOf(ngx_http_addr_conf_t), 24);
    try expectEqual(@sizeOf(ngx_http_conf_addr_t), 176);
    try expectEqual(@sizeOf(ngx_http_core_loc_conf_t), 704);
    try expectEqual(@sizeOf(ngx_http_headers_in_t), 312);
    try expectEqual(@sizeOf(ngx_http_request_body_t), 80);
    try expectEqual(@sizeOf(ngx_http_connection_t), 48);
    try expectEqual(@sizeOf(ngx_http_header_out_t), 24);

    try expectEqual(@sizeOf(ngx_http_request_t), 1320);
    try expectEqual(@offsetOf(ngx_http_request_t, "connection"), 8);
    try expectEqual(@offsetOf(ngx_http_request_t, "cleanup"), 1112);
    try expectEqual(@offsetOf(ngx_http_request_t, "flags0"), 1120);
    try expectEqual(@offsetOf(ngx_http_request_t, "flags1"), 1128);
    try expectEqual(@offsetOf(ngx_http_request_t, "state"), 1136);
    try expectEqual(@offsetOf(ngx_http_request_t, "host_end"), 1304);
    try expectEqual(@offsetOf(ngx_http_request_t, "flags2"), 1312);

    try expectEqual(@sizeOf(ngx_http_script_engine_t), 88);
    try expectEqual(@sizeOf(ngx_http_script_compile_t), 88);
    try expectEqual(@sizeOf(ngx_http_compile_complex_value_t), 32);
    try expectEqual(@sizeOf(ngx_http_script_regex_code_t), 72);
    try expectEqual(@sizeOf(ngx_http_script_regex_end_code_t), 16);

    try expectEqual(@sizeOf(c_uint), 4);
    try expectEqual(@sizeOf([4]c_uint), 16);
}
