daemon off;
error_log logs/error.log notice;
pid logs/nginx.pid;

events {
    worker_connections 256;
}

http {
    access_log logs/access.log;

    server {
        listen 8888;

        location /api/ {
            pgrest_pass "host=127.0.0.1 port=5432 dbname=nginz_bench user=nginz_test password=nginz_test_pass";
            pgrest_schemas "public";
            pgrest_pool_size 16;
        }
    }
}
